travis:
  secure:
    BINSTAR_TOKEN: X/KeOcroKYn4M3nCsdX9CsAr+gv/j5acGPXc1OAF9kMYoA4TzMelxzi/8S9CfNXIEDijPfWwEWdRUJ5qeD+ADYxWPitJPnSqL3gS6vyF18tMF4B9f1FeCqAggobzO6HFGM5Fvb7yCa3VM+QJmkCMkSGNBCLhCGh4YctwPZqoOpGgMHHdHZes4VlwXGRGWU36BL0/kXprqENFq9nWAO4/MvQOEDtzI4D537UzjUmBWI/Z1mWnsUiMe/pLG5534EqGUJlgajZa6vyVtZUUp3Kdn+R70fBYlamvs6TZwg5Dnb1pBDGUg2PuTPkQsCz3BxTRh6oHAd8AvjdaEKFZr2qoI9jAYzrnVVi0Jhf4o471HzV7FXm0PO8zRx8lUjn89PIED4eGpFPhwJQUYJSSnOt+RgAFXbKRGsUO6c6Tp98vzRijGrHEsOiFT8Op8Xh10L/auLsB8Oft2526qmZ5RcsLxrDW63LmnVMB64kr5Q+96LkaAOId8OHajxSu3+54EfaUSvt+WPkB0X+W4aoVoe5EBxDDQqEwIMbryQ9ZZ6M8BPr4V5L+CxPyxTT8PY7QXXFWlqy9oV3N9C87X3/rHS07yjuJkecOGlqopRjvYmi4n530FdkdE7rXI5OoRBrXnlHbkhD0ThQ0fp09X2JvX9DTBGe6FC/hZpQTY8sQGfK+z4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
