appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iWUcNwNEYSgs31uo+m80nv0xQEvo1oONfvYdYJMyUFp/NQLlVNvdl5xZR5AACmAHja6uhad603PoM/aMSR/8EbDOgkvuxCwsV+V/F0co3WbvvMF4rTUPG9lKYUTl6iMENZ4xbySXb13DnHPW2vWtasvZ4H0SdJlhaduIpwuLt2TsKCxjQGEQJCsfsttO6O0pZDsO3b4iHRbShPF/MmsgcAXBGAy3Uyt8BjKig54e0oD0XGBP+52RO6gMGyr+gSCKa1YZkIT9npVC0Pm7Vx63/c6rxJG9elgRGyKFGzCx+d6G5d39UYICe8uDtOWIlG//N8ZGp4FpdB9d6dOMmArWcL6CHKdKHKar6esTBVhk7aU1KfOOECD0MXqhCQyHEkC7ILfgHjwE+2QnADzW4LgC3mjzjMhydat7g9kor/CINN0DuwBZAMx48N5nHkhacvJ423zuJ9Nn0CD+gRxOMv1fhuJxWyWVHUtSVBYqGd4c5nhx9EABim5TGofPJrbCY+eJgBlDKW4gBAIDxdGH1s6m85wZ64/SG5q60bSEV1fylIIngsNX70KNcD4yJN+tDTkiv3YT9wH3MMu1H359kLSDUgcuAZI3VYyTsS6cYpWZw2LXK73IjY7EPmyO47fjI2tm527QzPGDs68FsxrqKmFytQ/goPZL+sRGYE4zS/zCMVs=}
conda_forge_output_validation: true
